# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Peggy Meter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Peggy Meter
  pod 'Charts'
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'SQLite.swift', '~> 0.11.4'
  pod 'ResearchKit'
end
